name: Andalan Aluminium
favicon: null
layout_spectrum: 0.74086
typography_spectrum: 0.65866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aaabaf'
    - '#2f2b28'
    - '#ec3237'
    - '#145388'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
