name: Andalan Aluminium
favicon: null
layout_spectrum: 0.84525
typography_spectrum: 0.50783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aaabaf'
    - '#2f2b28'
    - '#ec3237'
    - '#145388'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
